[project]
name = "ia-suporte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel Guerra", email = "gabrielcake9@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.22.0",
    "pydantic-settings>=2.15.0",
    "python-telegram-bot>=22.8",
    "uvicorn>=0.52.4",
]

[project.scripts]
ia-suporte = "ia_suporte:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
